# Generated by Django 4.2.7 on 2023-11-25 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapapp', '0004_alter_scraps_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scraps',
            name='image',
        ),
        migrations.RemoveField(
            model_name='scraps',
            name='user',
        ),
    ]
