# Generated by Django 4.2.7 on 2023-11-26 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapapp', '0006_scraps_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scraps',
            old_name='picture',
            new_name='image',
        ),
    ]
