# Generated by Django 5.0 on 2024-01-01 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapapp', '0010_rename_profile_pics_userprofile_profile_pic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapsfeauture',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
