# Generated by Django 5.0 on 2024-01-01 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapapp', '0011_alter_scrapsfeauture_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapsfeauture',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_feauture', to='scrapapp.category'),
        ),
        migrations.AlterField(
            model_name='scrapsfeauture',
            name='place',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='scrapsfeauture',
            name='price',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
