# Generated by Django 5.0 on 2024-01-01 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapapp', '0012_alter_scrapsfeauture_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapsfeauture',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_scraps', to='scrapapp.scraps'),
        ),
    ]
